<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Hello ${owner.name}!</title>
    <link href="/css/main.css" rel="stylesheet" />
</head>
<body>
<h2 class="hello-title">${owner.name}</h2>
<h2 class="hello-title">${owner.surname}</h2>
<h2 class="hello-title">${owner.address}</h2>
<h2 class="hello-title">${owner.afm}</h2>
<script src="/js/main.js"></script>
</body>

</html>